#!/usr/bin/env python3
"""
Smart-Educator Presentation Dashboard Generator
═══════════════════════════════════════════════
Reads presentation_results.json (generated by presentation_tester.py)
and creates an interactive HTML dashboard: presentation_report.html

Usage:
  1. First run: python presentation_tester.py --no-pause
  2. Then run:  python generate_presentation_dashboard.py
  3. Open:      presentation_report.html in your browser
"""

import json
import os
import sys
from datetime import datetime


def generate_dashboard(results_path: str, output_path: str):
    """Generate an interactive HTML dashboard from test results JSON."""

    with open(results_path, "r", encoding="utf-8") as f:
        results = json.load(f)

    total = len(results)
    passed = sum(1 for r in results if r["status"] == "PASS")
    failed = sum(1 for r in results if r["status"] == "FAIL")
    errors = sum(1 for r in results if r["status"] == "ERROR")
    total_time = sum(r["duration"] for r in results)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build test cards HTML
    test_cards = []
    for r in results:
        status_class = {"PASS": "pass", "FAIL": "fail", "ERROR": "error"}.get(r["status"], "")
        status_icon = {"PASS": "✅", "FAIL": "❌", "ERROR": "💥"}.get(r["status"], "?")
        layer_class = r["layer"].lower().replace("+", "-")

        output_html = "<br>".join(
            line.replace("<", "&lt;").replace(">", "&gt;").replace(" ", "&nbsp;")
            for line in r["output_lines"]
        )

        error_section = ""
        if r["error"]:
            error_section = f'<div class="error-msg">{r["error"]}</div>'

        files_html = " • ".join(f'<code>{f}</code>' for f in r["files_tested"])

        card = f"""
        <div class="test-card {status_class}" data-layer="{r['layer']}" data-status="{r['status']}">
            <div class="test-header" onclick="toggleCard(this)">
                <div class="test-meta">
                    <span class="test-num">#{r['test_number']}</span>
                    <span class="layer-badge {layer_class}">{r['layer']}</span>
                    <span class="test-name">{r['name']}</span>
                </div>
                <div class="test-status-area">
                    <span class="duration">{r['duration']:.2f}s</span>
                    <span class="status-badge {status_class}">{status_icon} {r['status']}</span>
                    <span class="chevron">▼</span>
                </div>
            </div>
            <div class="test-body">
                <div class="team-info">
                    <strong>Team:</strong> {r['layer_name']} &nbsp;|&nbsp;
                    <strong>Files:</strong> {files_html}
                </div>
                {error_section}
                <div class="output-block"><pre>{output_html}</pre></div>
            </div>
        </div>
        """
        test_cards.append(card)

    cards_html = "\n".join(test_cards)

    html = f"""<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart-Educator — Presentation Test Report</title>
    <style>
        :root {{
            --bg: #0d1117;
            --card-bg: #161b22;
            --border: #30363d;
            --text: #e6edf3;
            --text-dim: #8b949e;
            --accent: #58a6ff;
            --pass: #3fb950;
            --fail: #f85149;
            --error: #f0883e;
            --p1: #58a6ff;
            --p2: #3fb950;
            --p3: #f0883e;
            --star: #d2a8ff;
        }}

        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
        }}

        .header {{
            text-align: center;
            margin-bottom: 2rem;
            padding: 2rem;
            background: linear-gradient(135deg, #161b22 0%, #1c2333 100%);
            border: 1px solid var(--border);
            border-radius: 12px;
        }}

        .header h1 {{
            font-size: 2rem;
            margin-bottom: 0.5rem;
            background: linear-gradient(135deg, var(--accent), var(--p2));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }}

        .header .subtitle {{ color: var(--text-dim); }}
        .header .timestamp {{ color: var(--text-dim); font-size: 0.85rem; margin-top: 0.5rem; }}

        /* Stats bar */
        .stats-bar {{
            display: flex;
            gap: 1rem;
            justify-content: center;
            flex-wrap: wrap;
            margin: 1.5rem 0;
        }}

        .stat-card {{
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1rem 1.5rem;
            text-align: center;
            min-width: 120px;
        }}

        .stat-card .stat-value {{
            font-size: 2rem;
            font-weight: bold;
        }}

        .stat-card .stat-label {{
            font-size: 0.8rem;
            color: var(--text-dim);
            text-transform: uppercase;
        }}

        .stat-card.pass .stat-value {{ color: var(--pass); }}
        .stat-card.fail .stat-value {{ color: var(--fail); }}
        .stat-card.error .stat-value {{ color: var(--error); }}
        .stat-card.total .stat-value {{ color: var(--accent); }}
        .stat-card.time .stat-value {{ color: var(--text); font-size: 1.4rem; }}

        /* Filters */
        .filters {{
            display: flex;
            gap: 0.5rem;
            justify-content: center;
            flex-wrap: wrap;
            margin-bottom: 1.5rem;
        }}

        .filter-btn {{
            padding: 0.4rem 1rem;
            border: 1px solid var(--border);
            border-radius: 20px;
            background: var(--card-bg);
            color: var(--text);
            cursor: pointer;
            font-size: 0.85rem;
            transition: all 0.2s;
        }}

        .filter-btn:hover {{ border-color: var(--accent); }}
        .filter-btn.active {{ background: var(--accent); color: var(--bg); border-color: var(--accent); }}
        .filter-btn.p1 {{ border-color: var(--p1); }}
        .filter-btn.p1.active {{ background: var(--p1); }}
        .filter-btn.p2 {{ border-color: var(--p2); }}
        .filter-btn.p2.active {{ background: var(--p2); }}
        .filter-btn.p3 {{ border-color: var(--p3); }}
        .filter-btn.p3.active {{ background: var(--p3); }}

        /* Test cards */
        .test-card {{
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 8px;
            margin-bottom: 0.75rem;
            overflow: hidden;
            transition: all 0.2s;
        }}

        .test-card:hover {{ border-color: var(--accent); }}
        .test-card.pass {{ border-left: 3px solid var(--pass); }}
        .test-card.fail {{ border-left: 3px solid var(--fail); }}
        .test-card.error {{ border-left: 3px solid var(--error); }}

        .test-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0.8rem 1rem;
            cursor: pointer;
            user-select: none;
        }}

        .test-header:hover {{ background: rgba(255,255,255,0.03); }}

        .test-meta {{
            display: flex;
            align-items: center;
            gap: 0.6rem;
        }}

        .test-num {{
            color: var(--text-dim);
            font-weight: bold;
            font-size: 0.85rem;
        }}

        .layer-badge {{
            padding: 0.15rem 0.5rem;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: bold;
        }}

        .layer-badge.p1 {{ background: rgba(88,166,255,0.15); color: var(--p1); }}
        .layer-badge.p2 {{ background: rgba(63,185,80,0.15); color: var(--p2); }}
        .layer-badge.p3 {{ background: rgba(240,136,62,0.15); color: var(--p3); }}
        .layer-badge.p1-p2-p3 {{ background: rgba(210,168,255,0.15); color: var(--star); }}
        .layer-badge.p3-p1 {{ background: rgba(240,136,62,0.15); color: var(--p3); }}

        .test-name {{ font-weight: 500; }}

        .test-status-area {{
            display: flex;
            align-items: center;
            gap: 0.8rem;
        }}

        .duration {{ color: var(--text-dim); font-size: 0.85rem; }}

        .status-badge {{
            padding: 0.2rem 0.6rem;
            border-radius: 4px;
            font-size: 0.8rem;
            font-weight: bold;
        }}

        .status-badge.pass {{ background: rgba(63,185,80,0.15); color: var(--pass); }}
        .status-badge.fail {{ background: rgba(248,81,73,0.15); color: var(--fail); }}
        .status-badge.error {{ background: rgba(240,136,62,0.15); color: var(--error); }}

        .chevron {{
            color: var(--text-dim);
            transition: transform 0.2s;
            font-size: 0.8rem;
        }}

        .test-card.expanded .chevron {{ transform: rotate(180deg); }}

        .test-body {{
            display: none;
            padding: 0 1rem 1rem;
            border-top: 1px solid var(--border);
        }}

        .test-card.expanded .test-body {{ display: block; }}

        .team-info {{
            padding: 0.6rem 0;
            color: var(--text-dim);
            font-size: 0.85rem;
        }}

        .team-info code {{
            background: rgba(255,255,255,0.06);
            padding: 0.1rem 0.4rem;
            border-radius: 3px;
            font-size: 0.8rem;
        }}

        .error-msg {{
            background: rgba(248,81,73,0.1);
            border: 1px solid rgba(248,81,73,0.3);
            border-radius: 4px;
            padding: 0.6rem;
            margin: 0.5rem 0;
            color: var(--fail);
            font-size: 0.85rem;
        }}

        .output-block {{
            background: #0d1117;
            border: 1px solid var(--border);
            border-radius: 6px;
            padding: 1rem;
            margin-top: 0.5rem;
            overflow-x: auto;
        }}

        .output-block pre {{
            font-family: 'Fira Code', 'Consolas', monospace;
            font-size: 0.82rem;
            line-height: 1.5;
            white-space: pre-wrap;
            word-break: break-word;
        }}

        .phase-header {{
            padding: 1rem;
            margin: 1.5rem 0 0.75rem;
            border-radius: 8px;
            background: linear-gradient(135deg, rgba(88,166,255,0.08), transparent);
            border-left: 3px solid var(--accent);
        }}

        .phase-header h2 {{
            font-size: 1.1rem;
            color: var(--accent);
        }}

        .hidden {{ display: none !important; }}

        @media (max-width: 768px) {{
            body {{ padding: 1rem; }}
            .test-header {{ flex-direction: column; align-items: flex-start; gap: 0.5rem; }}
            .stats-bar {{ flex-direction: column; align-items: center; }}
        }}
    </style>
</head>
<body>

<div class="header">
    <h1>🧠 Smart-Educator — Presentation Test Report</h1>
    <div class="subtitle">Automated AI-driven educational assessment pipeline</div>
    <div class="timestamp">Generated: {timestamp}</div>
</div>

<div class="stats-bar">
    <div class="stat-card total">
        <div class="stat-value">{total}</div>
        <div class="stat-label">Total Tests</div>
    </div>
    <div class="stat-card pass">
        <div class="stat-value">{passed}</div>
        <div class="stat-label">Passed</div>
    </div>
    <div class="stat-card fail">
        <div class="stat-value">{failed}</div>
        <div class="stat-label">Failed</div>
    </div>
    <div class="stat-card error">
        <div class="stat-value">{errors}</div>
        <div class="stat-label">Errors</div>
    </div>
    <div class="stat-card time">
        <div class="stat-value">{total_time:.1f}s</div>
        <div class="stat-label">Total Time</div>
    </div>
</div>

<div class="filters">
    <button class="filter-btn active" onclick="filterAll(this)">All</button>
    <button class="filter-btn p1" onclick="filterLayer('P1', this)">🟦 P1 — API & Data</button>
    <button class="filter-btn p2" onclick="filterLayer('P2', this)">🟩 P2 — AI Pipeline</button>
    <button class="filter-btn p3" onclick="filterLayer('P3', this)">🟧 P3 — Infrastructure</button>
    <button class="filter-btn" onclick="filterStatus('PASS', this)">✅ Passed</button>
    <button class="filter-btn" onclick="filterStatus('FAIL', this)">❌ Failed</button>
    <button class="filter-btn" onclick="filterStatus('ERROR', this)">💥 Errors</button>
</div>

<div id="test-list">
    <div class="phase-header"><h2>🧱 Phase 1: Core Component Tests (1-5)</h2></div>
    {"".join(test_cards[:5])}

    <div class="phase-header"><h2>🔗 Phase 2: Integration Tests (6-10)</h2></div>
    {"".join(test_cards[5:10])}

    <div class="phase-header"><h2>🚀 Phase 3: End-to-End Project Usage Tests (11-18)</h2></div>
    {"".join(test_cards[10:])}
</div>

<script>
function toggleCard(header) {{
    header.parentElement.classList.toggle('expanded');
}}

function clearActive() {{
    document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
}}

function filterAll(btn) {{
    clearActive();
    btn.classList.add('active');
    document.querySelectorAll('.test-card').forEach(c => c.classList.remove('hidden'));
    document.querySelectorAll('.phase-header').forEach(h => h.classList.remove('hidden'));
}}

function filterLayer(layer, btn) {{
    clearActive();
    btn.classList.add('active');
    document.querySelectorAll('.test-card').forEach(c => {{
        const cardLayer = c.getAttribute('data-layer');
        if (cardLayer.includes(layer)) {{
            c.classList.remove('hidden');
        }} else {{
            c.classList.add('hidden');
        }}
    }});
    document.querySelectorAll('.phase-header').forEach(h => h.classList.remove('hidden'));
}}

function filterStatus(status, btn) {{
    clearActive();
    btn.classList.add('active');
    document.querySelectorAll('.test-card').forEach(c => {{
        if (c.getAttribute('data-status') === status) {{
            c.classList.remove('hidden');
        }} else {{
            c.classList.add('hidden');
        }}
    }});
    document.querySelectorAll('.phase-header').forEach(h => h.classList.remove('hidden'));
}}
</script>

</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"✅ Dashboard generated: {output_path}")
    print(f"   Open in browser to view the interactive report.")


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    results_path = os.path.join(script_dir, "presentation_results.json")
    output_path = os.path.join(script_dir, "presentation_report.html")

    if not os.path.exists(results_path):
        print("❌ No presentation_results.json found.")
        print("   Run the test suite first: python presentation_tester.py --no-pause")
        sys.exit(1)

    generate_dashboard(results_path, output_path)
