"""Pydantic schemas for file processing and document ingestion.

Defines the structure and validation rules for requests that chunk
and extract content from previously uploaded educational documents.
"""
from pydantic import BaseModel
from typing import Optional

# schema job is about processing file content ,content extraction,chunking 
# and validation 

class ProcessRequest(BaseModel):
    """
    Request payload for POST /api/v1/data/process/{project_id}.
    
    EXPLANATION OF FIELDS:
    - file_id: The unique filename generated by save_upload() during the upload step.
    - chunk_size: Maximum character length of each extracted passage/chunk.
      Default is 100 chars (can be increased to 400-1000 for standard curriculum lessons).
    - overlap_size: Number of characters shared between adjacent chunks (sliding window).
      Prevents cutting sentences or key scientific concepts in half across chunk borders.
    - do_reset: Optional flag for re-chunking or resetting cached chunks.
    """
    file_id: str
    chunk_size: Optional[int] = 100
    overlap_size: Optional[int] = 20
    do_reset: Optional[int] = 0

