"""Pydantic schemas for Question structures and types.

Defines the core data contract for assessment questions generated by Gemini
during Node 3 of the LangGraph pipeline (services/question_generator.py).
"""
from pydantic import BaseModel
from typing import Optional
from enum import Enum


class QuestionType(str, Enum):
    """
    Supported assessment item formats.
    
    EXPLANATION:
    - MCQ: Multiple-Choice Question (requires a choices array with 4 options).
    - TRUE_FALSE: Binary evaluation format (choices is None; correct_answer is "True" or "False").
    - SHORT_ANSWER: Open-ended recall or calculation question.
    """
    MCQ = "mcq"
    TRUE_FALSE = "true_false"
    SHORT_ANSWER = "short_answer"


class Question(BaseModel):
    """
    Complete specification of an AI-generated assessment item.
    
    EXPLANATION OF FIELDS:
    - question_text: The prompt presented to the student.
    - question_type: Enum (mcq, true_false, short_answer).
    - choices: List of 4 distinct options (only populated for MCQ, None for other types).
    - correct_answer: The canonical correct response.
    - explanation: Comprehensive pedagogical explanation justifying why the answer is correct.
    - difficulty: Declared Bloom's Taxonomy difficulty ("easy", "medium", "hard").
    - estimated_time_minutes: Estimated time in minutes expected for a student to answer.
    - related_LO_ids: Array of LO IDs that this question directly targets.
    - source_evidence: Verbatim quotation from the source text supporting the question/answer.
    """
    question_text: str
    question_type: QuestionType
    choices: Optional[list[str]] = None      # only for MCQ
    correct_answer: str
    explanation: str
    difficulty: str                          # "easy" / "medium" / "hard"
    estimated_time_minutes: int
    related_LO_ids: list[str]
    source_evidence: str